
name: build-push

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.dockerignore'
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  DOCKER_HUB_OWNER: phlummox

jobs:
  docker_build:
    name: docker build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: set docker image info
        id: info
        shell: bash
        run: |
          set -x
          IMAGE_NAME=$(make print-image-name)
          IMAGE_VERSION=$(make print-image-version)
          echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"
          echo "::set-output name=IMAGE_VERSION::${IMAGE_VERSION}"

      - name: check info ok
        run: |
          IMAGE_NAME="${{ steps.info.outputs.IMAGE_NAME }}"
          printf 'IMAGE_NAME is: <<%s>>\n' "${IMAGE_NAME}"
          if [ -z ${IMAGE_NAME} ]; then
            false
          fi

          IMAGE_VERSION="${{ steps.info.outputs.IMAGE_VERSION }}"
          printf 'IMAGE_VERSION is: <<%s>>\n' "${IMAGE_VERSION}"
          if [ -z ${IMAGE_VERSION} ]; then
            false
          fi

      - name: Log in to github Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


